apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
    # Postgres Config
    DB_HOST: fullstack-postgres                      
    DB_DRIVER: postgres
    DB_USER: test
    DB_PASSWORD: 123
    DB_NAME: simple-service
    DB_PORT: "5432" 
    #Go app PORT configuration
    PORT: "8080"
    POSTGRES_URL: postgres://test:123@fullstack-postgres:5432/simple-service?sslmode=disable # Currently hardcoding DB parameters, could use nested variables as future improvement
