apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: fullstack-postgres                          # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: fullstack-postgres
spec:
  ports:
    - name: db
      port: 5432
      targetPort: 5432                              # Exposing default port of 5432.
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: fullstack-postgres
    tier: postgres